# SPDX-FileCopyrightText: 2023-2024 Michael Reuter
#
# SPDX-License-Identifier: MIT

[battery_helper]
adafruit = [
    "adafruit_lc709203f",
    "adafruit_max1704x"
]

[mqtt_helper]
adafruit = [
    "adafruit_connection_manager",
    "adafruit_minimqtt"
]

[wifi_helper]
adafruit = [
    "adafruit_ntp"
]

[asyncio]
adafruit = [
    "adafruit_ticks"
]

[adafruit_requests]
adafruit = [
    "adafruit_connection_manager"
]

[adafuit_io]
adafruit = [
    "adafruit_connection_manager",
    "adafruit_minimqtt"
]

[defaults]
adafruit = [
    "adafruit_bus_device",
    "adafruit_register"
]

[adafruit]
module_location = "~/code/adafruit"
bundle = "adafruit-circuitpython-bundle-9.x-mpy"
is_directory = [
    "adafruit_io",
    "adafruit_bitmap_font",
    "adafruit_bus_device",
    "adafruit_display_text",
    "adafruit_minimqtt",
    "adafruit_onewire",
    "adafruit_register",
    "adafruit_seesaw",
    "asyncio",
]

[circuitpython]
module_location = "~/code/adafruit"
bundle = "circuitpython-community-bundle-9.x-mpy"
