# SPDX-FileCopyrightText: 2023 Michael Reuter
#
# SPDX-License-Identifier: MIT

code = "temperature_sensor.py"

[settings]
general = [
    "wifi",
    "mqtt"
]

[imports]
local = [
    "battery_helper",
    "mqtt_helper",
    "power_helper",
    "wifi_helper"
]
adafruit = [
    "adafruit_sht4x"
]
