# SPDX-FileCopyrightText: 2023 Michael Reuter
#
# SPDX-License-Identifier: MIT

code = "light_sensor.py"

[settings]
general = [
    "wifi",
    "mqtt"
]
local = "settings_lamptimer.toml"

[imports]
local = [
    "battery_helper",
    "mqtt_helper",
    "adafruit_veml7700"
]
adafruit = [
    "adafruit_ntp",
]
