# SPDX-FileCopyrightText: 2023-2024 Michael Reuter
#
# SPDX-License-Identifier: MIT

code = "light_sensor_lp.py"

[settings]
general = [
    "wifi",
    "mqtt"
]

[imports]
local = [
    "battery_helper",
    "mqtt_helper",
    "power_helper",
    "wifi_helper",
    "adafruit_veml7700"
]
