# SPDX-FileCopyrightText: 2023-2025 Michael Reuter
#
# SPDX-License-Identifier: MIT

code = "light_sensor.py"

[settings]
general = [
    "aio",
    "wifi"
]

[imports]
local = [
    "aio_helper",
    "battery_helper",
    "wifi_helper",
    "adafruit_veml7700"
]
