# SPDX-FileCopyrightText: 2023-2024 Michael Reuter
#
# SPDX-License-Identifier: MIT

code = "pool_temperature_sensor.py"

[settings]
general = [
    "wifi",
    "mqtt"
]

[imports]
local = [
    "battery_helper",
    "mqtt_helper",
    "power_helper",
    "wifi_helper"
]
adafruit = [
    "adafruit_onewire",
    "adafruit_ds18x20",
    "adafruit_thermistor"
]
